name: Release

on:
  push:
    branches: [main, dev]

env:
  BRANCH: "main"

jobs:
  release-create:
    permissions: write-all
    runs-on: ubuntu-latest

    outputs:
      release: ${{ steps.release.outputs.release_tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: release
        name: Create Release
        if: github.repository != 'EpitechPromo2026/B-FUN-500-TLS-5-2-glados-xavier.mitault'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "${{ github.ref }}" == 'refs/heads/main' ]]; then
            export GITHUB_OUTPUT=$GITHUB_OUTPUT
            bash ./.github/workflows/release.sh "${{ env.BRANCH }}"
          else
            echo "release_tag=0.0.0" >> $GITHUB_OUTPUT
          fi

  release-windows:
    runs-on: windows-latest
    needs: [release-create]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Haskell
        uses: haskell-actions/setup@v2
        with:
          enable-stack: true
          stack-version: 'latest'

      - name: Install dependencies
        run: ./scripts/InstallDepsWindows.ps1

      - name: Build
        run: make

      - name: Upload To Release
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ needs.release-create.outputs.release }} "./koaky.exe#koaky-windows.exe"

      - name: Upload To Artifact
        if: github.ref != 'refs/heads/main'
        uses: actions/upload-artifact@v3
        with:
          name: koaky.exe
          path: ./koaky.exe

  release-linux:
    runs-on: ubuntu-latest
    needs: [release-create]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Haskell
        uses: haskell-actions/setup@v2
        with:
          enable-stack: true
          stack-version: 'latest'

      - name: Install dependencies
        run: sudo ./scripts/InstallDepsLinux.bash

      - name: Build
        run: make

      - name: Rename
        run: mv koaky koaky-linux

      - name: Upload To Release
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ needs.release-create.outputs.release }} "./koaky-linux"

      - name: Upload To Artifact
        if: github.ref != 'refs/heads/main'
        uses: actions/upload-artifact@v3
        with:
          name: koaky-linux
          path: ./koaky-linux

  release-macos:
    runs-on: macos-latest
    needs: [release-create]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Haskell
        uses: haskell-actions/setup@v2
        with:
          enable-stack: true
          stack-version: 'latest'

      - name: Install dependencies
        run: ./scripts/InstallDepsMacos.zsh

      - name: Build
        run: make

      - name: Rename
        run: mv koaky koaky-macos

      - name: Upload To Release
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ needs.release-create.outputs.release }} "./koaky-macos"

      - name: Upload To Artifact
        if: github.ref != 'refs/heads/main'
        uses: actions/upload-artifact@v3
        with:
          name: koaky-macos
          path: ./koaky-macos
